/*
 * This source file was generated by the Gradle 'init' task
 */
package org.encapsulation;
import org.encapsulation;.User;
public class App {

    public static void main(String[] args) {

    User u = new User(); 
        u.setUser("Ahmed Khalid");
        u.setPassword("@IZja352xoj32423");
        u.setUuid("j3h17h13-j8ij381-k93k1k");
        
        System.out.println("This is the User Data:");
        System.out.println(u.getUser());
        System.out.println(u.getPassword());
        System.out.println(u.getUuid());
    }
}
